// Generated by Haxe 3.4.2 (git build master @ 890f8c7)
(function ($hx_exports) { "use strict";
var service_Service = $hx_exports["Service"] = function() {
};
service_Service.prototype = {
	testFunc: function() {
		console.log("testFunc!!!");
	}
};
service_Service.__rtti = "<class path=\"service.Service\" params=\"\">\n\t<testFunc public=\"1\" set=\"method\" line=\"10\"><f a=\"\"><x path=\"Void\"/></f></testFunc>\n\t<new public=\"1\" set=\"method\" line=\"6\"><f a=\"\"><x path=\"Void\"/></f></new>\n\t<meta>\n\t\t<m n=\":expose\"><e>\"Service\"</e></m>\n\t\t<m n=\":rtti\"/>\n\t</meta>\n</class>";
})(typeof exports != "undefined" ? exports : typeof window != "undefined" ? window : typeof self != "undefined" ? self : this);
