// Generated by Haxe 3.4.2 (git build master @ 890f8c7)
(function ($hx_exports) { "use strict";
$hx_exports["service"] = $hx_exports["service"] || {};
var moda_ModA = $hx_exports["ModA"] = function() {
	console.log("ModA.new");
};
moda_ModA.prototype = {
	modFunc: function() {
		this.service.testFunc();
	}
};
moda_ModA.__meta__ = { fields : { service : { inject : null}}};
moda_ModA.__rtti = "<class path=\"moda.ModA\" params=\"\">\n\t<service>\n\t\t<c path=\"service.Service\"/>\n\t\t<meta><m n=\"inject\"/></meta>\n\t</service>\n\t<modFunc public=\"1\" set=\"method\" line=\"13\"><f a=\"\"><x path=\"Void\"/></f></modFunc>\n\t<new public=\"1\" set=\"method\" line=\"8\"><f a=\"\"><x path=\"Void\"/></f></new>\n\t<meta>\n\t\t<m n=\":expose\"><e>\"ModA\"</e></m>\n\t\t<m n=\":rtti\"/>\n\t</meta>\n</class>";
})(typeof exports != "undefined" ? exports : typeof window != "undefined" ? window : typeof self != "undefined" ? self : this);
